--- #YAML:1.0
name:               Module-Extract-DeclaredMinimumPerl
version:            1.01_02
abstract:           Extract the version of Perl a module declares
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    feature:       0
    perl:          5.006
    PPI:           0
    Test::More:    0
    Test::Output:  0
    version:       0
resources:
    repository:  git://github.com/briandfoy/module-extract-declaredminimumperl.git
no_index:
    dir:
        - corpus
    directory:
        - t
        - inc
        - corpus
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - ppi
    - parsing
    - static-analysis
    - modules
