---
abstract: 'Extract the version of Perl a module declares'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - ppi
  - parsing
  - static-analysis
  - modules
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Extract-DeclaredMinimumPerl
no_index:
  directory:
    - corpus
requires:
  PPI: 0
  Test::More: 0
  Test::Output: 0
  feature: 0
  perl: 5.006
  version: 0
resources:
  repository: git://github.com/briandfoy/module-extract-declaredminimumperl.git
version: 1.02
